/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Window Icon
 #	author : miyako
 #	2016/02/14
 #
 # --------------------------------------------------------------------------------*/



// --- Window Icon
void WINDOW_SET_ICON(sLONG_PTR *pResult, PackagePtr pParams);
void WINDOW_Get_icon(sLONG_PTR *pResult, PackagePtr pParams);
